# confimap_yaml
apiVersion: v1
kind: ConfigMap
metadata:
 name: nginx-config
 namespace: nginx
data:
 index.html: |
   <html>
   <head><title>Hello from Dev</title></head>
   <body>
   <h1>Hello from Dev. This is a small dev change.</h1>
   </body>
   </html>