# confimap_yaml
apiVersion: v1
kind: ConfigMap
metadata:
 name: nginx-config
 namespace: nginx
data:
 index.html: |
   <html>
   <head><title>Hello from Prod</title></head>
   <body>
   <h1>Hello from PROD! Some change to just prod</h1>
   </body>
   </html>